### ISSUE TITLE
Sensitive Keyword

### ISSUE THREAD

**Issue by raminjefri** [Phumix/PHP-Directory-Search#1]
can help me clear sensitive keyword in project
and type .txt
example .txt .docx etc.
tnq

**Comment by Phumix** [comment]
What do you mean by this? Displaying multiple file extensions?

**Comment by raminjefri** [comment]
Greetings
This example is sensitive to uppercase and lowercase letters
If you could send me some examples
Or the example of the sort of change that can search all files and folders instantly thanks
raminjefri@gmail.com
